#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y  update
sudo apt-get install -y nginx 
sudo ufw all 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
