#!/usr/bin/env bash
# this script runs whoami command under the user passed as an argument
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi
target_user="$1"
sudo -u "$target_user" whoami
