#!/usr/bin/env bash
# this script configs nginx not to run webservers as root listens to port 8080
sed -i.bak "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i.bak "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
